group: robots_eval
task:
  # - nytimes_2023_2024_verbatim_128
  # - nytimes_2023_2024_verbatim_256
  # - nytimes_2023_2024_verbatim_512
  # - nytimes_mcm_2023_2024
  # - nytimes_mcq_2023_2024
  # - nytimes_verbatim
  # - nytimes_verbatim_256
  # - nytimes_verbatim_512
  # - nytimes_mcq
  # - nytimes_completion
  # - nytimes_verbatim_128_bleu_corpus
  # - nytimes_verbatim_256_bleu_corpus
  # - nytimes_verbatim_512_bleu_corpus
  - nytimes_2023_2024_verbatim_128_bleu_corpus
  - nytimes_2023_2024_verbatim_256_bleu_corpus
  - nytimes_2023_2024_verbatim_512_bleu_corpus

metadata:
  version: 1.0